"""empty message

Revision ID: 532f0e00fc37
Revises: 
Create Date: 2024-04-09 22:40:31.124373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '532f0e00fc37'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item'))
    )
    op.create_table('order',
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('create_by_microservice_id', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order'))
    )
    op.create_table('orderitem',
    sa.Column('order_fk', sa.Integer(), nullable=False),
    sa.Column('item_fk', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['item_fk'], ['item.id'], name=op.f('fk_orderitem_item_fk_item')),
    sa.ForeignKeyConstraint(['order_fk'], ['order.id'], name=op.f('fk_orderitem_order_fk_order')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orderitem'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orderitem')
    op.drop_table('order')
    op.drop_table('item')
    # ### end Alembic commands ###
